
actions:
  oreore:
    emails:
      - host: localhost
        port : 25
        from: root@example.com
        to:  vagrant@localhost
    scripts:
      - env | sort | logger -t snmptrap

defaults:
  url: http://example.com/

matches:
  - trap: IF-MIB::linkDown
    ipaddr: 192.0.2.100/32
    community: public
    bindings:
      index: RFC1213-MIB::ifIndex.*
      status: RFC1213-MIB::ifOperStatus.*
    conditions:
      index: { eq: [1, 2, 3, 4, 5] }
      status: { regexp: [あいうえお] }
    formats:
      subject: |
        {{.ipaddr}} Interface {{.index}} linkdown
      body: |
        Date: {{.date}}
        Ipaddr: {{.ipaddr}}
        Message: Interface {{.index}} linkdown
        ---
        {{.url}}
    action: oreore
    fallthrough: True
